apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cw_insights.name" . }}-cm
  namespace: {{ include "cw_insights.namespace" . }}
  labels: {{- include "cw_insights.labels" . | nindent 4 }}
data:
   cwagentconfig.json: {{ .Values.insights.config.agentconf | nindent 1 | quote }}
